"""init schema

Revision ID: 66b5d91e4b8a
Revises: 
Create Date: 2026-09-11 12:29:03.207033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66b5d91e4b8a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# ENUM 타입은 테이블보다 먼저 만들고, 테이블을 지운 뒤에 지운다.
# op.create_table 에 맡기면 같은 타입을 여러 테이블이 쓸 때 CREATE TYPE 이 중복 실행되고,
# downgrade 는 타입을 남겨서 재적용이 깨진다.
ENUM_TYPES = [
    postgresql.ENUM('WEEKLY', 'MONTHLY', name='feedback_period_type', create_type=False),
    postgresql.ENUM('PROCESSED', 'GENERAL', name='food_category', create_type=False),
    postgresql.ENUM('ACTIVE', 'COMPLETED', 'CANCELLED', name='goal_status', create_type=False),
    postgresql.ENUM('PENDING', 'REVIEWED', 'RESOLVED', name='handoff_status', create_type=False),
    postgresql.ENUM('DOSAGE_QUESTION', 'DISCONTINUATION_QUESTION', 'PRESCRIPTION_QUESTION', 'SEVERE_GI_SYMPTOM', 'OTHER', name='handoff_trigger_type', create_type=False),
    postgresql.ENUM('MODEL', 'USER', name='meal_item_source', create_type=False),
    postgresql.ENUM('ANALYZING', 'REVIEW_REQUIRED', 'EVALUATED', 'FAILED', name='meal_status', create_type=False),
    postgresql.ENUM('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', name='meal_type', create_type=False),
    postgresql.ENUM('PRE_DOSE', 'INITIAL', 'TITRATION', 'MAINTENANCE', name='medication_stage', create_type=False),
    postgresql.ENUM('SAFE', 'BLOCKED', 'REVIEW_REQUIRED', name='safety_status', create_type=False),
]


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    for enum_type in ENUM_TYPES:
        enum_type.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_refs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', postgresql.ENUM('PROCESSED', 'GENERAL', name='food_category', create_type=False), nullable=True),
    sa.Column('origin_type', sa.String(length=128), nullable=True),
    sa.Column('serving_size', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('calories', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('carbohydrate_g', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('protein_g', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('fat_g', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('fiber_g', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('cholesterol_mg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('saturated_fat_g', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('trans_fat_g', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('sodium_mg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('dataset_version', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_food_refs'))
    )
    op.create_index(op.f('ix_food_refs_name'), 'food_refs', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('auth_provider', sa.String(length=32), nullable=True),
    sa.Column('provider_user_id', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=False),
    sa.Column('restrictions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('fcm_token', sa.String(length=255), nullable=True),
    sa.Column('fcm_token_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notification_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('baseline_meal_kcal', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('auth_provider', 'provider_user_id', name=op.f('uq_users_auth_provider_provider_user_id'))
    )
    op.create_index('uq_users_fcm_token_active', 'users', ['fcm_token'], unique=True, postgresql_where=sa.text('fcm_token IS NOT NULL'))
    op.create_table('daily_feedbacks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('feedback_date', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('quantity_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('satiety_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('safety_status', postgresql.ENUM('SAFE', 'BLOCKED', 'REVIEW_REQUIRED', name='safety_status', create_type=False), server_default='REVIEW_REQUIRED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_feedbacks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_feedbacks')),
    sa.UniqueConstraint('user_id', 'feedback_date', name=op.f('uq_daily_feedbacks_user_id_feedback_date'))
    )
    op.create_table('long_term_feedbacks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('period_type', postgresql.ENUM('WEEKLY', 'MONTHLY', name='feedback_period_type', create_type=False), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('trend_summary', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('chart_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('safety_status', postgresql.ENUM('SAFE', 'BLOCKED', 'REVIEW_REQUIRED', name='safety_status', create_type=False), server_default='REVIEW_REQUIRED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_long_term_feedbacks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_long_term_feedbacks')),
    sa.UniqueConstraint('user_id', 'period_type', 'period_start', name=op.f('uq_long_term_feedbacks_user_id_period_type_period_start'))
    )
    op.create_index('ix_long_term_feedbacks_user_id_period_start', 'long_term_feedbacks', ['user_id', 'period_start'], unique=False)
    op.create_table('medication_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('drug_name', sa.String(length=128), nullable=False),
    sa.Column('dose_mg', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('injection_count', sa.Integer(), nullable=False),
    sa.Column('stage', postgresql.ENUM('PRE_DOSE', 'INITIAL', 'TITRATION', 'MAINTENANCE', name='medication_stage', create_type=False), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_medication_records_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medication_records'))
    )
    op.create_index('ix_medication_records_user_id_effective_from', 'medication_records', ['user_id', 'effective_from'], unique=False)
    op.create_index('uq_medication_records_current', 'medication_records', ['user_id'], unique=True, postgresql_where=sa.text('effective_to IS NULL'))
    op.create_table('user_goals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('target_weight_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'COMPLETED', 'CANCELLED', name='goal_status', create_type=False), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_goals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_goals'))
    )
    op.create_index(op.f('ix_user_goals_user_id'), 'user_goals', ['user_id'], unique=False)
    op.create_index('uq_user_goals_active', 'user_goals', ['user_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_table('user_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('appetite_level', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gi_symptoms', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_states_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_states'))
    )
    op.create_index('ix_user_states_user_id_recorded_at', 'user_states', ['user_id', sa.literal_column('recorded_at DESC')], unique=False)
    op.create_table('long_term_feedback_sources',
    sa.Column('long_term_feedback_id', sa.Uuid(), nullable=False),
    sa.Column('daily_feedback_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['daily_feedback_id'], ['daily_feedbacks.id'], name=op.f('fk_long_term_feedback_sources_daily_feedback_id_daily_feedbacks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['long_term_feedback_id'], ['long_term_feedbacks.id'], name=op.f('fk_long_term_feedback_sources_long_term_feedback_id_long_term_feedbacks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('long_term_feedback_id', 'daily_feedback_id', name=op.f('pk_long_term_feedback_sources'))
    )
    op.create_table('medication_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source_record_id', sa.Uuid(), nullable=True),
    sa.Column('drug_name', sa.String(length=128), nullable=True),
    sa.Column('dose_mg', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('injection_count', sa.Integer(), nullable=True),
    sa.Column('stage', postgresql.ENUM('PRE_DOSE', 'INITIAL', 'TITRATION', 'MAINTENANCE', name='medication_stage', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_record_id'], ['medication_records.id'], name=op.f('fk_medication_snapshots_source_record_id_medication_records'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_medication_snapshots_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medication_snapshots'))
    )
    op.create_index(op.f('ix_medication_snapshots_user_id'), 'medication_snapshots', ['user_id'], unique=False)
    op.create_table('meals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('medication_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('meal_type', postgresql.ENUM('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', name='meal_type', create_type=False), nullable=False),
    sa.Column('image_key', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('eaten_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', postgresql.ENUM('ANALYZING', 'REVIEW_REQUIRED', 'EVALUATED', 'FAILED', name='meal_status', create_type=False), server_default='ANALYZING', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('image_key IS NOT NULL OR raw_text IS NOT NULL', name=op.f('ck_meals_input_present')),
    sa.ForeignKeyConstraint(['medication_snapshot_id'], ['medication_snapshots.id'], name=op.f('fk_meals_medication_snapshot_id_medication_snapshots'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meals'))
    )
    op.create_index('ix_meals_user_id_eaten_at', 'meals', ['user_id', sa.literal_column('eaten_at DESC')], unique=False)
    op.create_table('meal_feedbacks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('meal_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('suggestions', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('safety_status', postgresql.ENUM('SAFE', 'BLOCKED', 'REVIEW_REQUIRED', name='safety_status', create_type=False), server_default='REVIEW_REQUIRED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], name=op.f('fk_meal_feedbacks_meal_id_meals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meal_feedbacks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_feedbacks')),
    sa.UniqueConstraint('meal_id', name=op.f('uq_meal_feedbacks_meal_id'))
    )
    op.create_index(op.f('ix_meal_feedbacks_user_id'), 'meal_feedbacks', ['user_id'], unique=False)
    op.create_table('meal_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meal_id', sa.Uuid(), nullable=False),
    sa.Column('food_ref_id', sa.String(length=64), nullable=True),
    sa.Column('original_food_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('estimated_amount_g', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('confirmed_amount_g', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('source', postgresql.ENUM('MODEL', 'USER', name='meal_item_source', create_type=False), server_default='MODEL', nullable=False),
    sa.Column('raw_ai_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('confidence IS NULL OR confidence BETWEEN 0 AND 1', name=op.f('ck_meal_items_confidence_range')),
    sa.ForeignKeyConstraint(['food_ref_id'], ['food_refs.id'], name=op.f('fk_meal_items_food_ref_id_food_refs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], name=op.f('fk_meal_items_meal_id_meals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_items'))
    )
    op.create_index(op.f('ix_meal_items_meal_id'), 'meal_items', ['meal_id'], unique=False)
    op.create_table('medical_handoff_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('meal_id', sa.Uuid(), nullable=True),
    sa.Column('user_state_id', sa.Uuid(), nullable=True),
    sa.Column('trigger_type', postgresql.ENUM('DOSAGE_QUESTION', 'DISCONTINUATION_QUESTION', 'PRESCRIPTION_QUESTION', 'SEVERE_GI_SYMPTOM', 'OTHER', name='handoff_trigger_type', create_type=False), nullable=False),
    sa.Column('trigger_reason', sa.Text(), nullable=True),
    sa.Column('original_input', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'REVIEWED', 'RESOLVED', name='handoff_status', create_type=False), server_default='PENDING', nullable=False),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], name=op.f('fk_medical_handoff_logs_meal_id_meals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_medical_handoff_logs_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_state_id'], ['user_states.id'], name=op.f('fk_medical_handoff_logs_user_state_id_user_states'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medical_handoff_logs'))
    )
    op.create_index('ix_medical_handoff_logs_status_detected_at', 'medical_handoff_logs', ['status', 'detected_at'], unique=False)
    op.create_table('qqs_evaluations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meal_id', sa.Uuid(), nullable=False),
    sa.Column('stage_at_evaluation', postgresql.ENUM('PRE_DOSE', 'INITIAL', 'TITRATION', 'MAINTENANCE', name='medication_stage', create_type=False), nullable=False),
    sa.Column('quantity_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('satiety_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], name=op.f('fk_qqs_evaluations_meal_id_meals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qqs_evaluations')),
    sa.UniqueConstraint('meal_id', name=op.f('uq_qqs_evaluations_meal_id'))
    )
    op.create_table('satiety_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meal_id', sa.Uuid(), nullable=False),
    sa.Column('satiety_before', sa.Integer(), nullable=True),
    sa.Column('satiety_after', sa.Integer(), nullable=True),
    sa.Column('hunger_return_minutes', sa.Integer(), nullable=True),
    sa.Column('user_comment', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('satiety_after IS NULL OR satiety_after BETWEEN 0 AND 100', name=op.f('ck_satiety_logs_satiety_after_range')),
    sa.CheckConstraint('satiety_before IS NULL OR satiety_before BETWEEN 0 AND 100', name=op.f('ck_satiety_logs_satiety_before_range')),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], name=op.f('fk_satiety_logs_meal_id_meals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_satiety_logs')),
    sa.UniqueConstraint('meal_id', name=op.f('uq_satiety_logs_meal_id'))
    )
    op.create_table('daily_feedback_sources',
    sa.Column('daily_feedback_id', sa.Uuid(), nullable=False),
    sa.Column('meal_feedback_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['daily_feedback_id'], ['daily_feedbacks.id'], name=op.f('fk_daily_feedback_sources_daily_feedback_id_daily_feedbacks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meal_feedback_id'], ['meal_feedbacks.id'], name=op.f('fk_daily_feedback_sources_meal_feedback_id_meal_feedbacks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('daily_feedback_id', 'meal_feedback_id', name=op.f('pk_daily_feedback_sources'))
    )
    op.create_table('user_corrections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meal_item_id', sa.Uuid(), nullable=False),
    sa.Column('original_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('corrected_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('corrected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meal_item_id'], ['meal_items.id'], name=op.f('fk_user_corrections_meal_item_id_meal_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_corrections'))
    )
    op.create_index(op.f('ix_user_corrections_meal_item_id'), 'user_corrections', ['meal_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_corrections_meal_item_id'), table_name='user_corrections')
    op.drop_table('user_corrections')
    op.drop_table('daily_feedback_sources')
    op.drop_table('satiety_logs')
    op.drop_table('qqs_evaluations')
    op.drop_index('ix_medical_handoff_logs_status_detected_at', table_name='medical_handoff_logs')
    op.drop_table('medical_handoff_logs')
    op.drop_index(op.f('ix_meal_items_meal_id'), table_name='meal_items')
    op.drop_table('meal_items')
    op.drop_index(op.f('ix_meal_feedbacks_user_id'), table_name='meal_feedbacks')
    op.drop_table('meal_feedbacks')
    op.drop_index('ix_meals_user_id_eaten_at', table_name='meals')
    op.drop_table('meals')
    op.drop_index(op.f('ix_medication_snapshots_user_id'), table_name='medication_snapshots')
    op.drop_table('medication_snapshots')
    op.drop_table('long_term_feedback_sources')
    op.drop_index('ix_user_states_user_id_recorded_at', table_name='user_states')
    op.drop_table('user_states')
    op.drop_index('uq_user_goals_active', table_name='user_goals', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index(op.f('ix_user_goals_user_id'), table_name='user_goals')
    op.drop_table('user_goals')
    op.drop_index('uq_medication_records_current', table_name='medication_records', postgresql_where=sa.text('effective_to IS NULL'))
    op.drop_index('ix_medication_records_user_id_effective_from', table_name='medication_records')
    op.drop_table('medication_records')
    op.drop_index('ix_long_term_feedbacks_user_id_period_start', table_name='long_term_feedbacks')
    op.drop_table('long_term_feedbacks')
    op.drop_table('daily_feedbacks')
    op.drop_index('uq_users_fcm_token_active', table_name='users', postgresql_where=sa.text('fcm_token IS NOT NULL'))
    op.drop_table('users')
    op.drop_index(op.f('ix_food_refs_name'), table_name='food_refs')
    op.drop_table('food_refs')

    bind = op.get_bind()
    for enum_type in ENUM_TYPES:
        enum_type.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
