"""add users height_cm

Revision ID: d69be47ad0e7
Revises: 66b5d91e4b8a
Create Date: 2026-09-15 16:02:21.414079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd69be47ad0e7'
down_revision: Union[str, Sequence[str], None] = '66b5d91e4b8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('height_cm', sa.Numeric(precision=4, scale=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'height_cm')
    # ### end Alembic commands ###
